export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCEED = 'SIGNUP_SUCCEED';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const SIGNOUT_START = 'SIGNOUT_START';
export const SIGNOUT_SUCCEED = 'SIGNOUT_SUCCEED';
export const SIGNOUT_FAIL = 'SIGNOUT_FAIL';

export const CONFIRM_LOGIND_START = 'CONFIRM_LOGIND_START';
export const CONFIRM_LOGIND_SUCCEED = 'CONFIRM_LOGIND_SUCCEED';
export const CONFIRM_LOGIND_FAIL = 'CONFIRM_LOGIND_FAIL';

export const GET_ALL_EVENTS_START = 'GET_ALL_EVENTS_START';
export const GET_ALL_EVENTS_SUCCEED = 'GET_ALL_EVENTS_SUCCEED';
export const GET_ALL_EVENTS_FAIL = 'GET_ALL_EVENTS_FAIL';

export const SET_LOGIN_USER_STATE = 'SET_LOGIN_USER_STATE';
