export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCEED = 'SIGNUP_SUCCEED';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const CONFIRM_LOGIND_START = '22222';
export const CONFIRM_LOGIND_SUCCEED = 'CONFIRM_LOGIND_SUCCEED';
export const CONFIRM_LOGIND_FAIL = 'CONFIRM_LOGIND_FAIL';
