export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCEED = 'SIGNUP_SUCCEED';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const CONFIRM_LOGIND_START = 'CONFIRM_LOGIND_START';
export const CONFIRM_LOGIND_SUCCEED = 'CONFIRM_LOGIND_SUCCEED';
export const CONFIRM_LOGIND_FAIL = 'CONFIRM_LOGIND_FAIL';

export const GET_ALL_EVENTS_START = 'GET_ALL_EVENTS_START';
export const GET_ALL_EVENTS_SUCCEED = 'GET_ALL_EVENTS_SUCCEED';
export const GET_ALL_EVENTS_FAIL = 'GET_ALL_EVENTS_FAIL';
